version: '3.0'

services:
  episen-sca-lal-front:
    image: lalves1410/episen-sca-lal-front-tp4
    deploy:
      mode: replicated
      replicas: 2
      resources:
        limits:
          cpus: '0.50'
          memory: 500M
        reservations:
          cpus: '0.25'
          memory: 200M
    restart: always
    ports:
      - "80-81:80"
    volumes:
        - './frontend-data:/var/log/nginx'
    healthcheck:
      test: ["CMD", "curl -f http://localhost:82 || exit 1"]
      timeout: 30s
      interval: 10m
      retries: 3

  episen-sca-lal-back:
    image: lalves1410/episen-sca-lal-back-tp4
    deploy:
      mode: replicated
      replicas: 2
      resources:
        limits:
          cpus: '0.50'
          memory: 500M
        reservations:
          cpus: '0.25'
          memory: 200M
    restart: always
    volumes:
        - './backend-data:/data/'
    ports:
      - "8080-8081:8080"
    healthcheck:
      test: ["CMD", "curl -f http://localhost:8080 || exit 1"]
      timeout: 30s
      interval: 10m
      retries: 3
